#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <process>" >&2
    exit 1
fi

for i in 128 256 512 1024 2048 4096 8192 16384; do
    GF="graph_settings.gnup"
    echo "set ylabel 'Number of Pages Touched'" > $GF
    echo "set xlabel 'Window Number'" >> $GF
    echo "set grid" >> $GF
    echo "set term png size 1200, 800" >> $GF
    echo "set output '"$1"_"$i"_plot.png'" >> $GF
    echo "set multiplot layout 2,2 rowsfirst \\" >> $GF
    echo "title 'Number of Pages Touched by Window \\" >> $GF
    echo "for the $1 with for a Window Size of $i'" >> $GF

    for j in 64 128 256 512; do
        ./sim $i $j $1 -s
        mv sim_history.csv "$1"_"$i"_"$j"_history.csv
        echo "set title 'Page Size: "$j"'" >> $GF
        echo "plot '"$1"_"$i"_"$j"_history.csv' \\" >> $GF
        echo "with points" >> $GF
    done

    echo "unset multiplot" >> $GF

    gnuplot "$GF"

    rm *.csv
    rm $GF

done   
